// 🤖 Vendors the published agent skills from a skills checkout into
// src/well-known/agent-skills/, and generates the discovery index.
//
// The skills live in carlosframework/skills, where they are authored and
// released as the Claude Code plugin. This script copies the platform-
// facing ones here byte-for-byte — the discovery index carries a sha256
// digest per SKILL.md, so the served bytes must be exactly the source
// repo's bytes — and writes index.json in the shape of the Agent Skills
// Discovery draft (https://github.com/cloudflare/agent-skills-discovery-rfc):
// one { name, type, description, url, digest } entry per skill, served at
// /.well-known/agent-skills/index.json.
//
// The vendored markdown can't carry a generated-by notice inline (the
// digests pin it to the source bytes), so index.json — the one file this
// script writes that looks hand-editable — names the whole tree as
// generated, in the same "//" convention sync-docs.mjs uses.
//
// Usage:
//   node hack/sync-skills.mjs <path-to-skills-checkout>
//   node hack/sync-skills.mjs <path> --check    # verify, write nothing
import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { mkdirSync, readdirSync, readFileSync, rmSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";

const [, , checkout, ...flags] = process.argv;
const check = flags.includes("--check");

if (!checkout) {
  console.error("usage: node hack/sync-skills.mjs <path-to-skills-checkout> [--check]");
  process.exit(2);
}

// The published set is an allowlist, not "everything in the repo":
// getting-started and building-carlos-apps are knowledge about CARLOS,
// which is what a well-known index on carlosframework.com is for.
// delegate is generic operator tooling that happens to live in the same
// plugin — an agent probing this domain to learn the platform has no use
// for it, so it stays plugin-only.
const PUBLISHED = ["getting-started", "building-carlos-apps"];

const SCHEMA = "https://schemas.agentskills.io/discovery/0.2.0/schema.json";
const dest = "src/well-known/agent-skills";
const versionDest = "src/_data/agentskillsversion.json";

const GENERATED = "Generated by hack/sync-skills.mjs from carlosframework/skills. " +
  "Everything under src/well-known/agent-skills/ is wiped and rewritten on the next " +
  "sync — change the source in the skills repo instead.";

function walk(dir) {
  const out = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const p = join(dir, entry.name);
    if (entry.isDirectory()) out.push(...walk(p));
    else out.push(p);
  }
  return out.sort();
}

let sha = "unknown";
try {
  sha = execFileSync("git", ["-C", checkout, "rev-parse", "HEAD"], { encoding: "utf8" }).trim();
} catch {
  console.error(`warning: could not read a sha from ${checkout}`);
}

// Single-line values only, like the spec's own reference implementation:
// both fields are one long line in practice, and not building a YAML
// parser is the point.
function frontmatter(raw, file) {
  const m = /^---\n([\s\S]*?)\n---\n/.exec(raw);
  if (!m) throw new Error(`${file}: no frontmatter`);
  const out = {};
  for (const line of m[1].split("\n")) {
    const i = line.indexOf(": ");
    if (i > 0) out[line.slice(0, i)] = line.slice(i + 2);
  }
  return out;
}

const skills = [];
const files = []; // [sourcePath, relativePathUnderDest]
for (const name of PUBLISHED) {
  const dir = join(checkout, "skills", name);
  try {
    statSync(join(dir, "SKILL.md"));
  } catch {
    console.error(`no skill at ${dir}`);
    process.exit(1);
  }
  const raw = readFileSync(join(dir, "SKILL.md"));
  const fm = frontmatter(raw.toString("utf8"), join(dir, "SKILL.md"));
  // The draft's limits, enforced at sync time so a bad index can't ship:
  // names are 1-64 chars of [a-z0-9-], descriptions at most 1024 chars.
  if (fm.name !== name) {
    console.error(`${name}: frontmatter name is ${JSON.stringify(fm.name)}`);
    process.exit(1);
  }
  if (!/^[a-z0-9][a-z0-9-]{0,63}$/.test(name)) {
    console.error(`${name}: not a valid skill name for the index`);
    process.exit(1);
  }
  if (!fm.description || fm.description.length > 1024) {
    console.error(`${name}: description missing or over 1024 chars`);
    process.exit(1);
  }
  skills.push({
    name,
    type: "skill-md",
    description: fm.description,
    url: `/.well-known/agent-skills/${name}/SKILL.md`,
    digest: "sha256:" + createHash("sha256").update(raw).digest("hex"),
  });
  for (const f of walk(dir)) files.push([f, join(name, relative(dir, f))]);
}

const indexOut =
  JSON.stringify({ "//": GENERATED, $schema: SCHEMA, skills }, null, 2) + "\n";

const versionOut = (shaValue) =>
  JSON.stringify(
    { "//": GENERATED, sha: shaValue, short: shaValue.slice(0, 7), skills: skills.length },
    null,
    2,
  ) + "\n";

if (check) {
  // A drifted vendored copy is a stale published skill, which is worse
  // than a failed build because the digests still verify — against the
  // old bytes.
  const problems = [];
  for (const [source, rel] of files) {
    let have = null;
    try {
      have = readFileSync(join(dest, rel));
    } catch {
      problems.push(`missing: ${rel}`);
      continue;
    }
    if (!have.equals(readFileSync(source))) problems.push(`differs: ${rel}`);
  }
  let vendored = [];
  try {
    vendored = walk(dest).map((p) => relative(dest, p)).filter((p) => p !== "index.json");
  } catch {
    vendored = [];
  }
  for (const rel of vendored) {
    if (!files.some(([, r]) => r === rel)) problems.push(`stale: ${rel}`);
  }
  try {
    if (readFileSync(join(dest, "index.json"), "utf8") !== indexOut) problems.push("differs: index.json");
  } catch {
    problems.push("missing: index.json");
  }
  // agentskillsversion.json is not compared byte-for-byte: its sha is
  // expected to change on every sync, and --check's job is catching a
  // vendored tree that has drifted from the checkout.
  if (problems.length) {
    console.error(`src/well-known/agent-skills is out of sync with ${checkout}:`);
    for (const p of problems) console.error(`  ${p}`);
    console.error(`run: node hack/sync-skills.mjs ${checkout}`);
    process.exit(1);
  }
  console.log(`agent skills in sync with ${sha.slice(0, 7)} (${skills.length} skills)`);
  process.exit(0);
}

rmSync(dest, { recursive: true, force: true });
for (const [source, rel] of files) {
  const target = join(dest, rel);
  mkdirSync(dirname(target), { recursive: true });
  writeFileSync(target, readFileSync(source));
}
writeFileSync(join(dest, "index.json"), indexOut);
writeFileSync(versionDest, versionOut(sha));
console.log(`synced ${skills.length} skills from ${sha.slice(0, 7)}`);
